[14.0][MIG] cb_medical_cancel: Migration to 14.0
tegin/cb-medical pull request #253
Opened 2022-12-05 16:59 UTC by kluna1998

2022-12-09 18:40 UTC, etobella requested changes

2022-12-09 18:40 UTC, etobella commented on cb_medical_cancel/views/medical_encounter_view.xml
> +                    groups="medical_base.group_medical_user"
Not needed.

2022-12-09 18:40 UTC, etobella commented on cb_medical_cancel/views/medical_sale_discount_views.xml
> +        parent="medical_base.group_medical_configurator"
No sense. this is not a menu :thinking:

2022-12-12 08:29 UTC, kluna1998 commented
Change done 😊  @etobella

2022-12-12 10:28 UTC, merged